apiVersion: v1
kind: Service
metadata:
  name: endorser-api-1
spec:
  type: {{ .Values.endorserApi1.service.type }}
  ports:
    - port: {{ .Values.endorserApi1.service.port }}
      targetPort: {{ .Values.endorserApi1.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: endorser-api-1
