apiVersion: v1
kind: Service
metadata:
  name: tenant-ui
  labels:
    app: tenant-ui
spec:
  selector:
    app: tenant-ui
  type: {{ .Values.tenantUi.service.type }}
  ports:
    - port: {{ .Values.tenantUi.service.port }}
      targetPort: {{ .Values.tenantUi.service.targetPort }}
      targetPort: http