apiVersion: v1
kind: Service
metadata:
  name: traction-db
  labels:
    app: traction-db
spec:
  type: {{ .Values.tractionDb.service.type }}
  ports:
    - port: {{ .Values.tractionDb.service.port }}
      targetPort: {{ .Values.tractionDb.service.targetPort }}
  selector:
    app: traction-db
