apiVersion: v1
kind: Secret
metadata:
  name: endorser-api-secrets
type: Opaque
data:
  ENDORSER_API_ADMIN_USER: ZW5kb3JzZXI=  
  ENDORSER_API_ADMIN_KEY: Y2hhbmdlLW1l  
  ACAPY_ADMIN_URL_API_KEY: Y2hhbmdlLW1l  
  ACAPY_WEBHOOK_URL_API_KEY: MTIzNA==  


  