apiVersion: v1
kind: ConfigMap
metadata:
  name: endorser-api-config
data:
  POSTGRESQL_HOST: "endorser-db"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_DB: "traction"
  ENVIRONMENT: "production"
  TRACTION_WEBHOOK_URL: "https://tractionapp.digicred.services/endorser-api/webhook"
  ENDORSER_API_PORT: "5000"
  ACAPY_ADMIN_URL: "https://tractionapp.digicred.services/endorser-agent-admin"

    