apiVersion: v1
kind: Service
metadata:
  name: traction-agent
  labels:
    app: traction-agent
spec:
  selector:
    app: traction-agent
  type: {{ .Values.tractionAgent.service.type }}
  ports: 
    - port: {{ .Values.tractionAgent.service.adminPort }}
      targetPort: {{ .Values.tractionAgent.service.adminTargetPort }}
      protocol: TCP
      name: admin-port
    - port: {{ .Values.tractionAgent.service.httpPort }}
      targetPort: {{ .Values.tractionAgent.service.httpTargetPort }}
      protocol: TCP
      name: http-port