apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: demo-tenant
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: honey@digicred.co
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
