apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: endorser-wallet
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  storageClassName: gp2