apiVersion: v1
kind: Service
metadata:
  name: endorser-db-1
  labels:
    app: endorser-db-1
spec:
  type: {{ .Values.endorserDb1.service.type }}
  ports:
    - port: {{ .Values.endorserDb1.service.port }}
      targetPort: {{ .Values.endorserDb1.service.targetPort }}
  selector:
    app: endorser-db-1
