apiVersion: v1
kind: Service
metadata:
  name: tenant-proxy
spec:
  selector:
    app: tenant-proxy
  ports:
    - port: {{ .Values.tenantProxy.service.port }}
      targetPort: {{ .Values.tenantProxy.service.targetPort }}
      name: http